export const whyJoinEOData = [
  {
    id: 1,
    icon: '/home/icon01@2x.png',
    title: 'Explore a world of opportunities at a global level.',
  },
  {
    id: 2,
    icon: '/home/icon02.png',
    title: 'Fuel your thirst of learning, learn and network with the best.',
  },
  {
    id: 3,
    icon: '/home/icon03.png',
    title: 'Build the world’s most influential community of entrepreneurs.',
  },
]

export const myEOGroupsData = [
  {
    id: 1,
    imageUrl: '/MyEOGroup/image01.png',
    bgColor: '#EEB876',
    textColor: '',
    link: 'https://chat.whatsapp.com/3ZVy1tc45PF8btncViqxjB',
    desc: 'Bespoke Meals at hard to book & New Restaurants',
  },
  {
    id: 2,
    imageUrl: '/MyEOGroup/image02.png',
    bgColor: '#C3DD9D',
    textColor: '',
    link: 'https://chat.whatsapp.com/DTSxT3MDQqeC3ZH6lToIkm',
    desc: 'Workout, Hike or Play with fellow members',
  },
  {
    id: 3,
    imageUrl: '/MyEOGroup/image03.png',
    bgColor: '#7BC0E9',
    textColor: '',
    link: 'https://chat.whatsapp.com/FovDfub7Oc6IRgn4VwZmk8',
    desc: 'Make an Outsized impact on your world',
  },
  {
    id: 4,
    imageUrl: '/MyEOGroup/image04.png',
    bgColor: '#E3983B',
    textColor: '',
    link: 'https://chat.whatsapp.com/JJuGANm3PvTJqIuFQ1nePd',
    desc: 'Dive deep into your spiritual side.',
  },
  {
    id: 5,
    imageUrl: '/MyEOGroup/image05.png',
    bgColor: '#DD91D8',
    textColor: '',
    link: 'https://chat.whatsapp.com/Ki3Ua5B14N1DVhCHjUigaG',
    desc: 'For all things Music & Concerts',
  },
  {
    id: 6,
    imageUrl: '/MyEOGroup/image06.png',
    bgColor: '#D2AA61',
    textColor: '',
    link: 'https://chat.whatsapp.com/D5HRAkgtu3rD8nyGs1MaK7',
    desc: 'For all things Pets!',
  },
  {
    id: 7,
    imageUrl: '/MyEOGroup/image07.png',
    bgColor: '#9F92DB',
    textColor: '',
    link: 'https://chat.whatsapp.com/Hvng5qquFMpI9JuC6ahdOX',
    desc: 'Showcase your Poker skills at the next EO Poker game',
  },
  {
    id: 8,
    imageUrl: '/MyEOGroup/image08.png',
    bgColor: '#FFE868',
    textColor: '',
    link: 'https://chat.whatsapp.com/JCIBIOsAKbO63b2GRWYGPn',
    desc: 'For things to do in Venice or Best Hotels in Ubud!',
  },
  {
    id: 9,
    imageUrl: '/MyEOGroup/image09.png',
    bgColor: '#F05822',
    textColor: '',
    link: 'https://chat.whatsapp.com/IaegU5bAU9v1gxRBuf95wa',
    desc: 'All things Cricket (RCB, Team India), Formula-1 & Football among others',
  },
  {
    id: 10,
    imageUrl: '/MyEOGroup/image10.png',
    bgColor: '#F08F22',
    textColor: '',
    link: 'https://chat.whatsapp.com/LOGp25r7Wd4Hd2GVx8TPPo',
    desc: 'Connect with insiders for relevent Industry Needs & Leads',
  },
  {
    id: 11,
    imageUrl: '/MyEOGroup/image11.png',
    bgColor: '#9EDADB',
    textColor: '',
    link: 'https://chat.whatsapp.com/CeEaNDeHOk37PaPwRf5HRs',
    desc: 'Connect for all things related to Health & Medical',
  },
]

export const myEOTeam = [
  {
    id: 1,
    imageUrl: '/team/image01.png',
    name: 'Yashovardhan Daga',
    designation: 'President',
  },
  {
    id: 2,
    imageUrl: '/team/image02.png',
    name: 'Nikhil Bhandarkar',
    designation: 'Learning Chair',
  },
  {
    id: 3,
    imageUrl: '/team/image03.png',
    name: 'Sanjeev Shenoy',
    designation: 'Co-Learning Chair',
  },
  {
    id: 4,
    imageUrl: '/team/image04.png',
    name: 'Uddhav Kanoria',
    designation: 'Membership Chair',
  },
  {
    id: 5,
    imageUrl: '/team/image05.png',
    name: 'Sanjay Wadhwa',
    designation: 'Governance Chair',
  },
  {
    id: 6,
    imageUrl: '/team/image06.png',
    name: 'Naren Dubey',
    designation: 'Forum Chair',
  },
  {
    id: 7,
    imageUrl: '/team/image07.png',
    name: 'Aditya Kumar',
    designation: 'MyEO Chair',
  },
  {
    id: 8,
    imageUrl: '/team/image08.png',
    name: 'Suraj Sreenath',
    designation: 'Suraj Sreenath',
  },
  {
    id: 9,
    imageUrl: '/team/image09.png',
    name: 'George Kuttukaran',
    designation: 'Integration Chair',
  },
  {
    id: 10,
    imageUrl: '/team/image10.png',
    name: 'Manish Giria',
    designation: 'Strategic Alliance Chair',
  },
  {
    id: 11,
    imageUrl: '/team/image11.png',
    name: 'Siddharth Goenka',
    designation: 'GSEA Chair',
  },
  {
    id: 12,
    imageUrl: '/team/image12.png',
    name: 'Narayan Rajan',
    designation: 'RIE Chair',
  },
  {
    id: 13,
    imageUrl: '/team/image13.png',
    name: 'Radhika George',
    designation: 'Spousal Chair',
  },
]
